SetCurrentUser middleware
torinos-io/api pull request #11
Opened 2017-07-16 15:49 UTC by wakwak3125

WHAT

2017-07-16 16:04 UTC, wakwak3125 commented
@creasty 
![please_cat](https://user-images.githubusercontent.com/10008419/28249175-db6b6970-6a8b-11e7-8dab-e4418b6f4dd0.gif)

2017-07-16 17:18 UTC, creasty requested changes
Reviewed

2017-07-16 17:18 UTC, creasty commented on server/middleware/current_user.go
> +
Remove empty line

2017-07-16 17:18 UTC, creasty commented on server/middleware/current_user.go
> +	currentuser = "CurrentUser"
`currentUserContextName`

2017-07-16 17:18 UTC, creasty commented on server/route/user.go
> +	user, exists := c.Get("currentUser")
Don't use bare `c.Get("currentUser")`.
This leads to... well, IT IS happening now... It always becomes `exists = false` as you set with `CurrentUser` and get by `currentUser`.

Create `middleware.GetCurrentUser(c)`.

2017-07-16 17:18 UTC, creasty commented on server/route/user.go
> +		c.JSON(http.StatusBadRequest, nil)
Usually we use `401 Unauthorized`

2017-07-16 17:18 UTC, creasty commented on service/oauth_service/find.go
> +	return s.UserStore.FindByAuthToken(token)
Not correct.
Multiple access token can be issued for a single user and it's likely to be changed 
after time elapsed.

So it's non-sense to compare two access token to identify user.
You'll need to lookup GitHub's user id (UUID) by access token, and then find a user with that UUID.

2017-07-16 18:56 UTC, creasty reviewed
Small points

2017-07-16 18:56 UTC, creasty commented on service/oauth_service/find.go
> +		SetDebug(s.Config.Env == "development").
Use `s.Config.IsDevelopment()`

2017-07-16 18:56 UTC, creasty commented on service/oauth_service/find.go
> +func (s *service) FindByAuthToken(token string) (*model.User, error) {
`FindByAccessToken`?

2017-07-16 18:56 UTC, creasty commented on server/route/user.go
> +		c.JSON(http.StatusUnauthorized, "Can not find authorized current user")
Use `.AbortWithStatus` with early exit.

```go
user := middleware.GetCurrentUser(c)
if user == nil {
    c.AbortWithStatus(http.StatusUnauthorized)
    return
}

c.JSON(http.StatusOK, user)
```

2017-07-16 18:56 UTC, creasty commented on server/middleware/current_user.go
> +	v, exists := c.Get(currentUserContextName)
Simplify by:

```go
if v, exists := c.Get(currentUserContextName); exists {
    if user, ok := v.(*model.User); ok {
        return user
    }
}

return nil
```

2017-07-16 20:51 UTC, wakwak3125 commented
@creasty Thank you 👍 
Could you check one more?

2017-07-16 21:12 UTC, creasty reviewed
The rest looks fine 👍

2017-07-16 21:12 UTC, creasty commented on server/middleware/current_user.go
> +		h := c.GetHeader("Authorization")
Conventionally we use the form of `Authorization: Bearer xxxxxxxxx`.

2017-07-17 05:38 UTC, wakwak3125 commented on server/middleware/current_user.go
> +		h := c.GetHeader("Authorization")
OK!

2017-07-17 06:03 UTC, wakwak3125 commented on server/middleware/current_user.go
> +		splited := strings.Split(h, "Bearer")
@creasty 
Is this correct approach to get Beare token?

2017-07-17 06:29 UTC, creasty commented on server/middleware/current_user.go
> +		splited := strings.Split(h, "Bearer")
Well, maybe not.. it leaves undesired space here.

```
"Bearer xxxxxxxxx" --> ["Bearer", " xxxxxxxxx"]
                                   ^
```

Take a look at notifications for example.
https://github.com/wantedly/notifications/blob/ea6a316558508abc529d7e059185c4abd654c03f/server/middleware/current_user.go#L61

2017-07-17 08:54 UTC, wakwak3125 commented on server/middleware/current_user.go
> +		splited := strings.Split(h, "Bearer")
@creasty Thank you very much.
I checked notifications and use that  🙏

2017-07-23 07:44 UTC, creasty approved these changes
LG 👍

2017-07-23 07:45 UTC, merged